# Generated by Django 3.0.5 on 2020-04-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200414_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upload',
        ),
    ]
